---
- hosts: all
  become: true
  vars_files:
    - cons.yml

  tasks:
    - name: Instalar prerequisito
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  #Configuracion de Apache
    - name: Instalar paquetes LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Creamos el documento raiz
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Configurar el VirtualHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Habilitamos el nuevo sitio web
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: desabilitamos el sitio de apache por default
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  # Configuracion de UFW
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  # Pasar nuestro directorio con index.php
    - name: Copiar directorio a servidor remoto
      copy:
        src: "paginasTarea/"
        dest: "/var/www/{{ http_host }}/"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
